name: campus_online
description: "Campus information and navigation app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.3.6
  go_router: ^13.2.0
  shared_preferences: ^2.2.0
  sliding_up_panel: ^2.0.0+1
  shimmer: ^3.0.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  uuid: ^4.3.3
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  debounce_throttle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.15
  flutter_native_splash: ^2.4.0
  freezed: ^3.0.6
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
