name: "campus_online"
description: "Campus information and navigation app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  shared_preferences: ^2.5.3
  sliding_up_panel: ^2.0.0+1
  shimmer: ^3.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core_web: ^2.22.0
  firebase_auth_web: ^5.14.2
  cloud_firestore_web: ^4.4.7
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  debounce_throttle: ^2.0.0
  js: ^0.7.1
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  flutter_native_splash: ^2.4.6      # Mevcut en son sürüm :contentReference[oaicite:0]{index=0}
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  #url_launcher: ^6.3.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/campus_online_logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/campus_online_logo.png
