name: "campus_online"
description: "Campus information and navigation app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  google_fonts: ^8.0.2
  json_annotation: ^4.9.0
  supabase_flutter: ^2.8.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
flutter_native_splash:
  color: "#2c2f60"
  image: lib/assets/app_acilis.png
  android: true
  ios: true
  web: false # Web için açılış ekranını devre dışı bırakıyoruz

  # Android 12 ve sonrası için özel ayarlar
  android_12:
    color: "#2c2f60"
    image: lib/assets/app_acilis.png # Android 12 için ikon
    # icon_background_color: "#2c2f60" # İkonun kendisi için bir arka plan gerekirse

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/campus-online_new-logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/campus-online_new-logo.jpeg
    - lib/assets/app_acilis.png
    - lib/assets/venue_images/
    - assets/images/
